### ISSUE TITLE
`wrappers` is missing when installing using pip

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [lebrice/SimpleParsing#6]
**Describe the bug**
I tried to install using pip. When trying to import I get this:
```
% python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simple_parsing
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serdyuk/miniconda3/lib/python3.7/site-packages/simple_parsing/__init__.py", line 5, in <module>
    from .parsing import ArgumentParser, ConflictResolution
  File "/home/serdyuk/miniconda3/lib/python3.7/site-packages/simple_parsing/parsing.py", line 23, in <module>
    from .wrappers import DataclassWrapper, FieldWrapper
ModuleNotFoundError: No module named 'simple_parsing.wrappers'
>>> 
```

**To Reproduce**
1. `pip install simple_parsing`
2. `python -c "import simple-parsing"

**Expected behavior**
It doesn't crash.

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04
 - miniconda 3
 - python 3.7.4

**Comment by lebrice** [comment]
Fixed (I hope) by https://github.com/lebrice/SimpleParsing/pull/8#issue-361202735
